"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
cwd = { fg = "#b9c8da", bold = true }

hovered = { fg = "#cee5ff", bg = "#0d4a73" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#b9c8da", italic = true }
find_position = { fg = "#d3bfe6", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#9bcbfa" }

syntect_theme = "~/.config/yazi/catppuccin_Mocha.tmTheme"

[mode]
normal_main = { fg = "#003353", bg = "#9bcbfa", bold = true }
normal_alt = { fg = "#0d4a73", bg = "#e0e2e8" ,bold = true}

select_main = { fg = "#233240", bg = "#b9c8da", bold = true }
select_alt = { fg = "#3a4857", bg = "#e0e2e8" ,bold = true}

unset_main = { fg = "#382a49", bg = "#d3bfe6", bold = true }
unset_alt = { fg = "#4f4061", bg = "#e0e2e8" ,bold = true}

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#9bcbfa" }
perm_read = { fg = "#d5c871" }
perm_write = { fg = "#a1c9fd" }
perm_exec = { fg = "#fbb0d8" }
perm_sep = { fg = "#e0e2e8" }

[which]
mask = { bg = "#1c2024" }
cand = { fg = "#9bcbfa" }
rest = { bg = "#1c2024" }
desc = { fg = "#b9c8da" }
separator = "  "
separator_style = { fg = "#d3bfe6" }

[notify]
title_info = { fg = "#91d5ad" }
title_warn = { fg = "#d5c871" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#b9c8da" },

  # Videos
  { mime = "video/*", fg = "#d3bfe6" },
  { mime = "audio/*", fg = "#d3bfe6" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#9bcbfa", bold = true },
  { name = "*/", fg = "#b9c8da", bold = true },
]
