"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
cwd = { fg = "#e7bdb6", bold = true }

hovered = { fg = "#ffdad5", bg = "#73342b" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#e7bdb6", italic = true }
find_position = { fg = "#dec38c", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#ffb4a9" }

syntect_theme = "~/.config/yazi/catppuccin_Mocha.tmTheme"

[mode]
normal_main = { fg = "#561e17", bg = "#ffb4a9", bold = true }
normal_alt = { fg = "#73342b", bg = "#f1dedc" ,bold = true}

select_main = { fg = "#442925", bg = "#e7bdb6", bold = true }
select_alt = { fg = "#5d3f3b", bg = "#f1dedc" ,bold = true}

unset_main = { fg = "#3e2e04", bg = "#dec38c", bold = true }
unset_alt = { fg = "#574419", bg = "#f1dedc" ,bold = true}

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#ffb4a9" }
perm_read = { fg = "#f5bd6f" }
perm_write = { fg = "#b8c4ff" }
perm_exec = { fg = "#ffb2b6" }
perm_sep = { fg = "#f1dedc" }

[which]
mask = { bg = "#271d1c" }
cand = { fg = "#ffb4a9" }
rest = { bg = "#271d1c" }
desc = { fg = "#e7bdb6" }
separator = "  "
separator_style = { fg = "#dec38c" }

[notify]
title_info = { fg = "#b1d18a" }
title_warn = { fg = "#f5bd6f" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#e7bdb6" },

  # Videos
  { mime = "video/*", fg = "#dec38c" },
  { mime = "audio/*", fg = "#dec38c" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#ffb4a9", bold = true },
  { name = "*/", fg = "#e7bdb6", bold = true },
]
