"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
cwd = { fg = "#cfc7a2", bold = true }

hovered = { fg = "#f4e489", bg = "#514700" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#cfc7a2", italic = true }
find_position = { fg = "#a8d0b6", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#d7c770" }

syntect_theme = "~/.config/yazi/catppuccin_Mocha.tmTheme"

[mode]
normal_main = { fg = "#383100", bg = "#d7c770", bold = true }
normal_alt = { fg = "#514700", bg = "#e8e2d4" ,bold = true}

select_main = { fg = "#353117", bg = "#cfc7a2", bold = true }
select_alt = { fg = "#4c472b", bg = "#e8e2d4" ,bold = true}

unset_main = { fg = "#123725", bg = "#a8d0b6", bold = true }
unset_alt = { fg = "#2a4e3a", bg = "#e8e2d4" ,bold = true}

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#d7c770" }
perm_read = { fg = "#e0c56d" }
perm_write = { fg = "#99ccfa" }
perm_exec = { fg = "#ffb3b3" }
perm_sep = { fg = "#e8e2d4" }

[which]
mask = { bg = "#222017" }
cand = { fg = "#d7c770" }
rest = { bg = "#222017" }
desc = { fg = "#cfc7a2" }
separator = "  "
separator_style = { fg = "#a8d0b6" }

[notify]
title_info = { fg = "#b1d18a" }
title_warn = { fg = "#e0c56d" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#cfc7a2" },

  # Videos
  { mime = "video/*", fg = "#a8d0b6" },
  { mime = "audio/*", fg = "#a8d0b6" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#d7c770", bold = true },
  { name = "*/", fg = "#cfc7a2", bold = true },
]
