"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
cwd = { fg = "#e6bdbd", bold = true }

hovered = { fg = "#ffdada", bg = "#723337" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#e6bdbd", italic = true }
find_position = { fg = "#e6c08d", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#ffb3b5" }

syntect_theme = "~/.config/yazi/catppuccin_Mocha.tmTheme"

[mode]
normal_main = { fg = "#561d22", bg = "#ffb3b5", bold = true }
normal_alt = { fg = "#723337", bg = "#f0dede" ,bold = true}

select_main = { fg = "#44292a", bg = "#e6bdbd", bold = true }
select_alt = { fg = "#5d3f40", bg = "#f0dede" ,bold = true}

unset_main = { fg = "#432c05", bg = "#e6c08d", bold = true }
unset_alt = { fg = "#5c421a", bg = "#f0dede" ,bold = true}

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#ffb3b5" }
perm_read = { fg = "#f5bd6f" }
perm_write = { fg = "#b8c4ff" }
perm_exec = { fg = "#ffb2bd" }
perm_sep = { fg = "#f0dede" }

[which]
mask = { bg = "#271d1d" }
cand = { fg = "#ffb3b5" }
rest = { bg = "#271d1d" }
desc = { fg = "#e6bdbd" }
separator = "  "
separator_style = { fg = "#e6c08d" }

[notify]
title_info = { fg = "#b1d18a" }
title_warn = { fg = "#f5bd6f" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#e6bdbd" },

  # Videos
  { mime = "video/*", fg = "#e6c08d" },
  { mime = "audio/*", fg = "#e6c08d" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#ffb3b5", bold = true },
  { name = "*/", fg = "#e6bdbd", bold = true },
]
