"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
cwd = { fg = "#e7bdb0", bold = true }

hovered = { fg = "#ffdbcf", bg = "#72351f" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#e7bdb0", italic = true }
find_position = { fg = "#d6c68e", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#ffb59c" }

syntect_theme = "~/.config/yazi/catppuccin_Mocha.tmTheme"

[mode]
normal_main = { fg = "#55200b", bg = "#ffb59c", bold = true }
normal_alt = { fg = "#72351f", bg = "#f1dfd9" ,bold = true}

select_main = { fg = "#442a21", bg = "#e7bdb0", bold = true }
select_alt = { fg = "#5d4036", bg = "#f1dfd9" ,bold = true}

unset_main = { fg = "#393005", bg = "#d6c68e", bold = true }
unset_alt = { fg = "#51461a", bg = "#f1dfd9" ,bold = true}

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#ffb59c" }
perm_read = { fg = "#f5bd6f" }
perm_write = { fg = "#b8c4ff" }
perm_exec = { fg = "#ffb3b3" }
perm_sep = { fg = "#f1dfd9" }

[which]
mask = { bg = "#271d1a" }
cand = { fg = "#ffb59c" }
rest = { bg = "#271d1a" }
desc = { fg = "#e7bdb0" }
separator = "  "
separator_style = { fg = "#d6c68e" }

[notify]
title_info = { fg = "#b1d18a" }
title_warn = { fg = "#f5bd6f" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#e7bdb0" },

  # Videos
  { mime = "video/*", fg = "#d6c68e" },
  { mime = "audio/*", fg = "#d6c68e" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#ffb59c", bold = true },
  { name = "*/", fg = "#e7bdb0", bold = true },
]
