"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
cwd = { fg = "#b0cccb", bold = true }

hovered = { fg = "#9cf1f1", bg = "#004f50" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#b0cccb", italic = true }
find_position = { fg = "#b3c8e9", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#80d4d5" }

syntect_theme = "~/.config/yazi/catppuccin_Mocha.tmTheme"

[mode]
normal_main = { fg = "#003737", bg = "#80d4d5", bold = true }
normal_alt = { fg = "#004f50", bg = "#dde4e3" ,bold = true}

select_main = { fg = "#1b3435", bg = "#b0cccb", bold = true }
select_alt = { fg = "#324b4b", bg = "#dde4e3" ,bold = true}

unset_main = { fg = "#1d314b", bg = "#b3c8e9", bold = true }
unset_alt = { fg = "#344863", bg = "#dde4e3" ,bold = true}

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#80d4d5" }
perm_read = { fg = "#d5c871" }
perm_write = { fg = "#99ccfa" }
perm_exec = { fg = "#fbb0d8" }
perm_sep = { fg = "#dde4e3" }

[which]
mask = { bg = "#1a2121" }
cand = { fg = "#80d4d5" }
rest = { bg = "#1a2121" }
desc = { fg = "#b0cccb" }
separator = "  "
separator_style = { fg = "#b3c8e9" }

[notify]
title_info = { fg = "#91d5ad" }
title_warn = { fg = "#d5c871" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#b0cccb" },

  # Videos
  { mime = "video/*", fg = "#b3c8e9" },
  { mime = "audio/*", fg = "#b3c8e9" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#80d4d5", bold = true },
  { name = "*/", fg = "#b0cccb", bold = true },
]
