"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
cwd = { fg = "#c4c4dd", bold = true }

hovered = { fg = "#e0e0ff", bg = "#3d4279" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#c4c4dd", italic = true }
find_position = { fg = "#e7b9d5", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#bdc2ff" }

syntect_theme = "~/.config/yazi/catppuccin_Mocha.tmTheme"

[mode]
normal_main = { fg = "#262b61", bg = "#bdc2ff", bold = true }
normal_alt = { fg = "#3d4279", bg = "#e4e1e9" ,bold = true}

select_main = { fg = "#2d2f42", bg = "#c4c4dd", bold = true }
select_alt = { fg = "#444559", bg = "#e4e1e9" ,bold = true}

unset_main = { fg = "#45263c", bg = "#e7b9d5", bold = true }
unset_alt = { fg = "#5e3c53", bg = "#e4e1e9" ,bold = true}

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#bdc2ff" }
perm_read = { fg = "#f5bd6f" }
perm_write = { fg = "#b3c5ff" }
perm_exec = { fg = "#fbb0d8" }
perm_sep = { fg = "#e4e1e9" }

[which]
mask = { bg = "#1f1f25" }
cand = { fg = "#bdc2ff" }
rest = { bg = "#1f1f25" }
desc = { fg = "#c4c4dd" }
separator = "  "
separator_style = { fg = "#e7b9d5" }

[notify]
title_info = { fg = "#91d5ad" }
title_warn = { fg = "#f5bd6f" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#c4c4dd" },

  # Videos
  { mime = "video/*", fg = "#e7b9d5" },
  { mime = "audio/*", fg = "#e7b9d5" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#bdc2ff", bold = true },
  { name = "*/", fg = "#c4c4dd", bold = true },
]
