"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
show_hidden = false 
show_symlink = true
cwd = { fg = "#c3c5dd", bold = true }

hovered = { fg = "#dde1ff", bg = "#384379" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#c3c5dd", italic = true }
find_position = { fg = "#e5bad8", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#b9c3ff" }

syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*", block = true, for = "windows" },
]

[mode]
normal_main = { fg = "#212c61", bg = "#b9c3ff", bold = true }
normal_alt = { fg = "#384379", bg = "#e3e1e9" }

select_main = { fg = "#2c2f42", bg = "#c3c5dd", bold = true }
select_alt = { fg = "#434659", bg = "#e3e1e9" }

unset_main = { fg = "#44263e", bg = "#e5bad8", bold = true }
unset_alt = { fg = "#5c3c55", bg = "#e3e1e9" }

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#b9c3ff" }
perm_read = { fg = "#f5bd6f" }
perm_write = { fg = "#b1c5ff" }
perm_exec = { fg = "#fbb0d8" }
perm_sep = { fg = "#e3e1e9" }

[which]
mask = { bg = "#1f1f25" }
cand = { fg = "#b9c3ff" }
rest = { bg = "#1f1f25" }
desc = { fg = "#c3c5dd" }
separator = "  "
separator_style = { fg = "#e5bad8" }

[notify]
title_info = { fg = "#91d5ad" }
title_warn = { fg = "#f5bd6f" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#c3c5dd" },

  # Videos
  { mime = "video/*", fg = "#e5bad8" },
  { mime = "audio/*", fg = "#e5bad8" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#b9c3ff", bold = true },
  { name = "*/", fg = "#c3c5dd", bold = true },
]
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
