"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
show_hidden = false 
show_symlink = true
cwd = { fg = "#cbc2dc", bold = true }

hovered = { fg = "#e8ddff", bg = "#4c3e75" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#cbc2dc", italic = true }
find_position = { fg = "#efb8c8", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#cfbdfe" }

syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*", block = true, for = "windows" },
]

[mode]
normal_main = { fg = "#35275d", bg = "#cfbdfe", bold = true }
normal_alt = { fg = "#4c3e75", bg = "#e6e1e9" }

select_main = { fg = "#332d41", bg = "#cbc2dc", bold = true }
select_alt = { fg = "#494458", bg = "#e6e1e9" }

unset_main = { fg = "#492532", bg = "#efb8c8", bold = true }
unset_alt = { fg = "#633b49", bg = "#e6e1e9" }

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#cfbdfe" }
perm_read = { fg = "#f5bd6f" }
perm_write = { fg = "#b8c4ff" }
perm_exec = { fg = "#fbb0d8" }
perm_sep = { fg = "#e6e1e9" }

[which]
mask = { bg = "#211f24" }
cand = { fg = "#cfbdfe" }
rest = { bg = "#211f24" }
desc = { fg = "#cbc2dc" }
separator = "  "
separator_style = { fg = "#efb8c8" }

[notify]
title_info = { fg = "#91d5ad" }
title_warn = { fg = "#f5bd6f" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#cbc2dc" },

  # Videos
  { mime = "video/*", fg = "#efb8c8" },
  { mime = "audio/*", fg = "#efb8c8" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#cfbdfe", bold = true },
  { name = "*/", fg = "#cbc2dc", bold = true },
]
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
