"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
show_hidden = false 
show_symlink = true
cwd = { fg = "#b1ccc6", bold = true }

hovered = { fg = "#9ef2e3", bg = "#005047" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#b1ccc6", italic = true }
find_position = { fg = "#accae5", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#82d5c7" }

syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*", block = true, for = "windows" },
]

[mode]
normal_main = { fg = "#003731", bg = "#82d5c7", bold = true }
normal_alt = { fg = "#005047", bg = "#dde4e1" }

select_main = { fg = "#1c3530", bg = "#b1ccc6", bold = true }
select_alt = { fg = "#334b47", bg = "#dde4e1" }

unset_main = { fg = "#143349", bg = "#accae5", bold = true }
unset_alt = { fg = "#2d4a60", bg = "#dde4e1" }

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#82d5c7" }
perm_read = { fg = "#d5c871" }
perm_write = { fg = "#99ccfa" }
perm_exec = { fg = "#fbb0d8" }
perm_sep = { fg = "#dde4e1" }

[which]
mask = { bg = "#1a211f" }
cand = { fg = "#82d5c7" }
rest = { bg = "#1a211f" }
desc = { fg = "#b1ccc6" }
separator = "  "
separator_style = { fg = "#accae5" }

[notify]
title_info = { fg = "#91d5ad" }
title_warn = { fg = "#d5c871" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#b1ccc6" },

  # Videos
  { mime = "video/*", fg = "#accae5" },
  { mime = "audio/*", fg = "#accae5" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#82d5c7", bold = true },
  { name = "*/", fg = "#b1ccc6", bold = true },
]
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
