"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
show_hidden = false 
show_symlink = true
cwd = { fg = "#b2cbd1", bold = true }

hovered = { fg = "#a6eeff", bg = "#004e5b" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#b2cbd1", italic = true }
find_position = { fg = "#bdc5eb", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#83d2e4" }

syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*", block = true, for = "windows" },
]

[mode]
normal_main = { fg = "#00363f", bg = "#83d2e4", bold = true }
normal_alt = { fg = "#004e5b", bg = "#dee3e5" }

select_main = { fg = "#1c3439", bg = "#b2cbd1", bold = true }
select_alt = { fg = "#334a50", bg = "#dee3e5" }

unset_main = { fg = "#272f4d", bg = "#bdc5eb", bold = true }
unset_alt = { fg = "#3d4565", bg = "#dee3e5" }

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#83d2e4" }
perm_read = { fg = "#d5c871" }
perm_write = { fg = "#99ccfa" }
perm_exec = { fg = "#fbb0d8" }
perm_sep = { fg = "#dee3e5" }

[which]
mask = { bg = "#1b2122" }
cand = { fg = "#83d2e4" }
rest = { bg = "#1b2122" }
desc = { fg = "#b2cbd1" }
separator = "  "
separator_style = { fg = "#bdc5eb" }

[notify]
title_info = { fg = "#91d5ad" }
title_warn = { fg = "#d5c871" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#b2cbd1" },

  # Videos
  { mime = "video/*", fg = "#bdc5eb" },
  { mime = "audio/*", fg = "#bdc5eb" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#83d2e4", bold = true },
  { name = "*/", fg = "#b2cbd1", bold = true },
]
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
