"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = true
sort_reverse = true
sort_dir_first = true
show_hidden = false 
show_symlink = true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*", block = true, for = "windows" },
]

# [open]
# prepend_rules = [
#
# 	{ name = "*/", use = ["edit", "open"] },
#
# 	{ mime = "text/*", use = ["edit"] },
# 	{ name = "*.json", use = "edit" },
#
# 	# Multiple openers for a single rule
# 	{ name = "*.html", use = ["open", "edit"] },
#
# ]
# [input]
# cursor_blink = false
#
# # cd
# cd_title  = "Change directory:"
# cd_origin = "top-center"
# cd_offset = [ 0, 2, 50, 3 ]
#
# # create
# create_title  = [ "Create:", "Create (dir):" ]
# create_origin = "top-center"
# create_offset = [ 0, 2, 50, 3 ]
#
# # rename
# rename_title  = "Rename:"
# rename_origin = "hovered"
# rename_offset = [ 0, 1, 50, 3 ]
#
# # filter
# filter_title  = "Filter:"
# filter_origin = "top-center"
# filter_offset = [ 0, 2, 50, 3 ]
#
# # find
# find_title  = [ "Find next:", "Find previous:" ]
# find_origin = "top-center"
# find_offset = [ 0, 2, 50, 3 ]
#
# # search
# search_title  = "Search via {n}:"
# search_origin = "top-center"
# search_offset = [ 0, 2, 50, 3 ]
#
# # shell
# shell_title  = [ "Shell:", "Shell (block):" ]
# shell_origin = "top-center"
# shell_offset = [ 0, 2, 50, 3 ]
#
# [confirm]
# # trash
# trash_title 	= "Trash {n} selected file{s}?"
# trash_origin	= "center"
# trash_offset	= [ 0, 0, 70, 20 ]
#
# # delete
# delete_title 	= "Permanently delete {n} selected file{s}?"
# delete_origin	= "center"
# delete_offset	= [ 0, 0, 70, 20 ]
#
# # overwrite
# overwrite_title   = "Overwrite file?"
# overwrite_content = "Will overwrite the following file:"
# overwrite_origin  = "center"
# overwrite_offset  = [ 0, 0, 50, 15 ]
#
# # quit
# quit_title   = "Quit?"
# quit_content = "The following tasks are still running, are you sure you want to quit?"
# quit_origin  = "center"
# quit_offset  = [ 0, 0, 50, 15 ]
#
# [pick]
# open_title  = "Open with:"
# open_origin = "hovered"
# open_offset = [ 0, 1, 50, 7 ]
#
# [which]
# sort_by      	 = "none"
# sort_sensitive = false
# sort_reverse 	 = false
# sort_translit  = false

# [log]
# enabled = false

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
