"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
show_hidden = false 
show_symlink = true
cwd = { fg = "#e7bdb9", bold = true }

hovered = { fg = "#ffdad6", bg = "#73332f" }
preview_hovered = { underline = true, bold = true }

find_keyword = { fg = "#e7bdb9", italic = true }
find_position = { fg = "#e1c28c", bg = "reset", italic = true }


border_symbol = "│"
border_style = { fg = "#ffb3ad" }

syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = "nvim %*", block = true, for = "windows" },
]

[mode]
normal_main = { fg = "#571e1b", bg = "#ffb3ad", bold = true }
normal_alt = { fg = "#73332f", bg = "#f1dedc" }

select_main = { fg = "#442927", bg = "#e7bdb9", bold = true }
select_alt = { fg = "#5d3f3c", bg = "#f1dedc" }

unset_main = { fg = "#402d04", bg = "#e1c28c", bold = true }
unset_alt = { fg = "#584419", bg = "#f1dedc" }

[status]
separator_open = ""
separator_close = ""

perm_type = { fg = "#ffb3ad" }
perm_read = { fg = "#f5bd6f" }
perm_write = { fg = "#b8c4ff" }
perm_exec = { fg = "#ffb2b8" }
perm_sep = { fg = "#f1dedc" }

[which]
mask = { bg = "#271d1c" }
cand = { fg = "#ffb3ad" }
rest = { bg = "#271d1c" }
desc = { fg = "#e7bdb9" }
separator = "  "
separator_style = { fg = "#e1c28c" }

[notify]
title_info = { fg = "#b1d18a" }
title_warn = { fg = "#f5bd6f" }
title_error = { fg = "#ffb4ab" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#e7bdb9" },

  # Videos
  { mime = "video/*", fg = "#e1c28c" },
  { mime = "audio/*", fg = "#e1c28c" },

  # Archives
  { mime = "application/zip", fg = "#ffb4ab" },
  { mime = "application/gzip", fg = "#ffb4ab" },
  { mime = "application/x-tar", fg = "#ffb4ab" },
  { mime = "application/x-bzip", fg = "#ffb4ab" },
  { mime = "application/x-bzip2", fg = "#ffb4ab" },
  { mime = "application/x-7z-compressed", fg = "#ffb4ab" },
  { mime = "application/x-rar", fg = "#ffb4ab" },

  # Fallback
  { name = "*", fg = "#ffb3ad", bold = true },
  { name = "*/", fg = "#e7bdb9", bold = true },
]
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
