[config]
# [config.wallpaper]
# command = "swww"
# arguments = ["img", "--transition-type", "center"]
# set = false


# [templates.waybar]
# input_path = '~/.config/matugen/templates/waybar-colors.css'
# output_path = '~/.config/waybar/colors.css'
# post_hook = 'pkill -SIGUSR2 waybar'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = 'kitten themes --reload-in=all matugen'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/config.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/matugen_colors.conf'
# post_hook = 'hyprctl reload;hyprshade on vibrance'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-colors.toml'
output_path = '~/.config/yazi/theme.toml'

# [templates.neovim]
# input_path = '~/.config/matugen/templates/nvim-catppuccin.lua'
# output_path = '~/.cache/nvim/matugen_catppuccin_colors.lua'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors'
output_path = '~/.config/cava/config'

[templates.ags]
input_path = '~/.config/matugen/templates/ags-colors.scss'
output_path = '~/.config/ags/styles/matugen-colors.scss'
post_hook = 'astal reloadcss'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-colors.conf'
output_path = '~/.tmux.conf.d/colors.conf'
post_hook = '~/.config/matugen/scripts/tmux_reload.sh'


[config.custom_colors]
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
orange = "#fab387"
purple = "#cba6f7"
