title-hidden = true
frame = "none"
srgb = true

# normal = ["CodeNewRoman Nerd Font Mono"]
[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[font]
# normal = ["CodeNewRoman Nerd Font Mono"]
# normal = { family = "Monaspace Radon"}
size = 12

[[font.normal]]
family = "Maple Mono NF CN"

[[font.italic]]
family = "Maple Mono NF CN"

[[font.bold_italic]]
family = "Maple Mono NF CN"


# [font.features]
# "Maple Mono NF CN" = [ "+cv03", "+ss01", "+ss02",  "+ss04", "+ss05", "+ss07", "zero" ]
#cv03 ss01 ss02 ss04 ss05 ss07 zero
