return {
	"catppuccin/nvim",
	name = "catppuccin",
	priority = 1000,
	opts = {
		term_colors = true,
		transparent_background = vim.g.transparent(),
		integrations = {
			cmp = true,
			blink_cmp = true,
			gitsigns = true,
			nvimtree = true,
			treesitter = true,
			notify = true,
			mason = true,
			rainbow_delimiters = true,
			snacks = true,
			-- mini = {
			--   enabled = true,
			--   indentscope_color = '',
			-- },
			dropbar = {
				enabled = true,
				color_mode = true, -- enable color for kind's texts, not just kind's icons
			},
			fidget = true,
			noice = true,
			symbols_outline = true,
			lsp_trouble = true,
			which_key = true,
		},
		-- transparent_background = transparent_background,
		styles = { -- Handles the styles of general hi groups (see `:h highlight-args`):
			comments = { "italic" }, -- Change the style of comments
			conditionals = { "italic" },
			loops = {},
			functions = { "italic" },
			keywords = { "italic", "bold" },
			strings = {},
			variables = {},
			numbers = {},
			booleans = { "italic" },
			properties = {},
			types = {},
			operators = {},
		},
		color_overrides = {
			mocha = {
				rosewater = "#ffb59d",
				flamingo = "#ffb59d",
				pink = "#fbb0d8",
				mauve = "#c9bfff",
				red = "#fbb0d8",
				maroon = "#fbb0d8",
				peach = "#fab387",
				yellow = "#d5c871",
				green = "#e0bbde",
				teal = "#91d5ad",
				sky = "#b0c6ff",
				sapphire = "#b0c6ff",
				blue = "#b0c6ff",
				lavender = "#b0c6ff",
				text = "#e2e2e9",
				subtext1 = "#bbbbbb",
				subtext0 = "#aaaaaa",
				overlay2 = "#999999",
				overlay1 = "#888888",
				overlay0 = "#777777",
				surface2 = "#666666",
				surface1 = "#555555",
				surface0 = "#444444",
				base = "#1a1b20",
				mantle = "#0c0e13",
				crust = "#121318",
			},
			latte = {
				rosewater = "#fab387",
				flamingo = "#fab387",
				pink = "#f38ba8",
				mauve = "#c9bfff",
				red = "#f38ba8",
				maroon = "#f38ba8",
				peach = "#fab387",
				yellow = "#4f4700",
				green = "#e0bbde",
				teal = "#a6e3a1",
				sky = "#b0c6ff",
				sapphire = "#b0c6ff",
				blue = "#b0c6ff",
				lavender = "#b0c6ff",
				text = "#e2e2e9",
				subtext1 = "#555555",
				subtext0 = "#666666",
				overlay2 = "#777777",
				overlay1 = "#888888",
				overlay0 = "#999999",
				surface2 = "#aaaaaa",
				surface1 = "#bbbbbb",
				surface0 = "#cccccc",
				base = "#1a1b20",
				mantle = "#0c0e13",
				crust = "#121318",
			},
		},

		highlight_overrides = {
			mocha = function(mocha)
				return {
					DiagnosticUnderlineError = { undercurl = true, sp = mocha.red },
					DiagnosticUnderlineWarn = { undercurl = true, sp = mocha.yellow },
					DiagnosticUnderlineInfo = { undercurl = true, sp = mocha.green },
					DiagnosticUnderlineHint = { undercurl = true, sp = mocha.sky },
				}
			end,
		},
	},
}
